[package]
name = "nested_init_test"
version = "0.1.0"
edition = "2021"

[features]
dummy_touch = []
dummy_touch_indirect = []

[dependencies]
ctor = { version = "0.2.8", features = ["used_linker"] }
libc-print = "0.1.23"
